#!/bin/bash
#
# generate-env.sh
# Interactive script to generate .env file with cloud service configuration
#
# Usage: ./Scripts/generate-env.sh
#        or: make gen
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
DEFAULT_ENDPOINT="https://translator-api.zanderwang.com"

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║           AITranslator Environment Configuration           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if .env already exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file already exists.${NC}"
    # Read existing values
    EXISTING_SECRET=$(grep -E "^AITRANSLATOR_CLOUD_SECRET=" .env 2>/dev/null | cut -d'=' -f2- || echo "")
    EXISTING_ENDPOINT=$(grep -E "^AITRANSLATOR_CLOUD_ENDPOINT=" .env 2>/dev/null | cut -d'=' -f2- || echo "")
    
    read -p "Overwrite existing configuration? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

echo ""
echo -e "${GREEN}Step 1/2: Cloud Endpoint${NC}"
echo "─────────────────────────"
echo "Enter your Cloudflare Worker endpoint URL."
echo -e "Default: ${BLUE}${DEFAULT_ENDPOINT}${NC}"
echo ""

read -p "Endpoint URL [press Enter for default]: " INPUT_ENDPOINT
ENDPOINT="${INPUT_ENDPOINT:-$DEFAULT_ENDPOINT}"

echo ""
echo -e "${GREEN}Step 2/2: HMAC Secret${NC}"
echo "──────────────────────"
echo "Enter the HMAC signing secret (must match APP_SECRET in your Worker)."
echo "This should be a 64-character hex string."
echo ""
echo -e "${YELLOW}Options:${NC}"
echo "  1. Enter existing secret"
echo "  2. Generate new secret (you'll need to update Worker too)"
echo ""

read -p "Choose [1/2]: " -n 1 -r SECRET_CHOICE
echo ""

if [[ $SECRET_CHOICE == "2" ]]; then
    # Generate new secret
    NEW_SECRET=$(openssl rand -hex 32)
    echo ""
    echo -e "${GREEN}Generated new secret:${NC}"
    echo -e "${BLUE}${NEW_SECRET}${NC}"
    echo ""
    echo -e "${YELLOW}Important: You must also update your Cloudflare Worker:${NC}"
    echo "  cd Workers"
    echo "  wrangler secret put APP_SECRET"
    echo "  # Paste the same secret when prompted"
    echo ""
    read -p "Press Enter to continue..."
    SECRET="$NEW_SECRET"
else
    echo ""
    read -p "Enter HMAC secret: " SECRET
    
    # Validate secret format (should be hex string)
    if [[ ! "$SECRET" =~ ^[0-9a-fA-F]+$ ]]; then
        echo -e "${YELLOW}Warning: Secret doesn't appear to be a hex string.${NC}"
        read -p "Continue anyway? [y/N] " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
    fi
fi

# Write .env file
cat > .env << EOF
# AITranslator Environment Configuration
# Generated by: make gen
# Generated at: $(date)

# Cloud Service Configuration
AITRANSLATOR_CLOUD_SECRET=${SECRET}
AITRANSLATOR_CLOUD_ENDPOINT=${ENDPOINT}
EOF

echo ""
echo -e "${GREEN}✓ Created .env file${NC}"

# Update Base.xcconfig default endpoint if different from default
if [ "$ENDPOINT" != "$DEFAULT_ENDPOINT" ]; then
    echo ""
    echo -e "${YELLOW}Note: Your endpoint differs from the default in Base.xcconfig.${NC}"
    echo "The endpoint in .env will be used (via Secrets.xcconfig)."
fi

# Run secrets injection
echo ""
echo "Running secrets injection..."
./Scripts/inject-secrets.sh

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗"
echo "║                    Configuration Complete!                   ║"
echo "╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Summary:"
echo "  Endpoint: ${ENDPOINT}"
echo "  Secret:   ${SECRET:0:8}...${SECRET: -8} (${#SECRET} chars)"
echo ""
echo "Next steps:"
echo "  1. Open AITranslator.xcodeproj in Xcode"
echo "  2. Build and run the app"
echo ""
if [[ $SECRET_CHOICE == "2" ]]; then
    echo -e "${YELLOW}Don't forget to update your Worker secret!${NC}"
    echo "  cd Workers && wrangler secret put APP_SECRET"
    echo ""
fi
