#!/bin/bash
#
# inject-secrets.sh
# Unified secrets injection script for AITranslator
#
# This script generates Configuration/Secrets.xcconfig from environment variables.
# It works across all build environments:
#   - Xcode Cloud (via ci_post_clone.sh)
#   - Local development (via make secrets or direct invocation)
#   - Contributors (via make secrets with default/custom values)
#
# Usage:
#   ./Scripts/inject-secrets.sh
#
# Environment Variables (in order of priority):
#   1. Shell environment variables
#   2. .env file in project root
#   3. Default values
#
# Required Variables:
#   AITRANSLATOR_CLOUD_SECRET  - HMAC signing secret for cloud service
#
# Optional Variables:
#   AITRANSLATOR_CLOUD_TOKEN      - Authentication token for cloud API
#   AITRANSLATOR_CLOUD_ENDPOINT   - Cloud service endpoint URL

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Determine script and project directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# For Xcode Cloud, use CI_PRIMARY_REPOSITORY_PATH if available
if [ -n "$CI_PRIMARY_REPOSITORY_PATH" ]; then
    PROJECT_ROOT="$CI_PRIMARY_REPOSITORY_PATH"
    echo -e "${BLUE}[Xcode Cloud]${NC} Using CI_PRIMARY_REPOSITORY_PATH: $PROJECT_ROOT"
fi

CONFIG_DIR="${PROJECT_ROOT}/Configuration"
SECRETS_XCCONFIG="${CONFIG_DIR}/Secrets.xcconfig"
ENV_FILE="${PROJECT_ROOT}/.env"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  AITranslator Secrets Injection${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Load .env file if it exists and we're not in CI
load_env_file() {
    if [ -f "$ENV_FILE" ]; then
        echo -e "${GREEN}[OK]${NC} Loading .env file..."
        # Export variables from .env file, but don't override existing env vars
        set -a
        while IFS='=' read -r key value || [ -n "$key" ]; do
            # Skip comments and empty lines
            [[ "$key" =~ ^#.*$ ]] && continue
            [[ -z "$key" ]] && continue
            # Remove leading/trailing whitespace and quotes
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
            # Only set if not already set in environment
            if [ -z "${!key}" ]; then
                export "$key=$value"
            fi
        done < "$ENV_FILE"
        set +a
    else
        echo -e "${YELLOW}[INFO]${NC} No .env file found, using environment variables only"
    fi
}

# Load .env file
load_env_file

# Set defaults
DEFAULT_ENDPOINT="https://translator-api.zanderwang.com"

# Get values with fallbacks
CLOUD_SECRET="${AITRANSLATOR_CLOUD_SECRET:-}"
CLOUD_TOKEN="${AITRANSLATOR_CLOUD_TOKEN:-}"
CLOUD_ENDPOINT="${AITRANSLATOR_CLOUD_ENDPOINT:-$DEFAULT_ENDPOINT}"

# Escape // in URLs for xcconfig (// is treated as comment)
# Replace :// with :$()/$()/ to prevent xcconfig from treating it as a comment
CLOUD_ENDPOINT_ESCAPED=$(echo "$CLOUD_ENDPOINT" | sed 's|://|:$()/$()/|')

# Ensure Configuration directory exists
mkdir -p "$CONFIG_DIR"

# Generate Secrets.xcconfig
echo -e "${GREEN}[OK]${NC} Generating Secrets.xcconfig..."

cat > "$SECRETS_XCCONFIG" << EOF
// Secrets.xcconfig
// AUTO-GENERATED by inject-secrets.sh - DO NOT EDIT MANUALLY
// This file is git-ignored. Regenerate with: make secrets
//
// Generated at: $(date '+%Y-%m-%d %H:%M:%S')

// MARK: - Cloud Service Secrets

// HMAC signing secret for cloud service authentication
AITRANSLATOR_CLOUD_SECRET = ${CLOUD_SECRET}

// Authentication token for cloud API
AITRANSLATOR_CLOUD_TOKEN = ${CLOUD_TOKEN}

// Cloud service endpoint URL
AITRANSLATOR_CLOUD_ENDPOINT = ${CLOUD_ENDPOINT_ESCAPED}
EOF

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Configuration Summary${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  Output: ${BLUE}${SECRETS_XCCONFIG}${NC}"
echo ""
echo -e "  CLOUD_SECRET:      $([ -n "$CLOUD_SECRET" ] && echo -e "${GREEN}Set (${#CLOUD_SECRET} chars)${NC}" || echo -e "${YELLOW}Not set${NC}")"
echo -e "  CLOUD_TOKEN:       $([ -n "$CLOUD_TOKEN" ] && echo -e "${GREEN}Set (${#CLOUD_TOKEN} chars)${NC}" || echo -e "${YELLOW}Not set${NC}")"
echo -e "  CLOUD_ENDPOINT:    ${BLUE}${CLOUD_ENDPOINT}${NC}"
echo ""

# Validation warnings
if [ -z "$CLOUD_SECRET" ]; then
    echo -e "${YELLOW}[WARNING]${NC} AITRANSLATOR_CLOUD_SECRET is not set."
    echo -e "          The built-in cloud service will not work without it."
    echo -e "          Set it in .env file or as an environment variable."
    echo ""
fi

echo -e "${GREEN}[DONE]${NC} Secrets injection complete!"
echo ""
echo -e "Next steps:"
echo -e "  1. Ensure Xcode project is configured to use Configuration/*.xcconfig files"
echo -e "  2. Build the project: ${BLUE}xcodebuild -scheme AITranslator${NC}"
echo ""
